
// List of words
const words = [
  "abandon",
  "ability",
  "able",
  "about",
  "above",
 "abroad",
  "absolute",
  "absolutely",
  "academic",
  "accept",
  "acceptable",
  "access",
  "accident",
  "accommodation",
  "accompany",
  "according to",
  "account",
  "accurate",
  "accuse",
  "achieve",
  "achievement",
  "acknowledge",
  "acquire",
  "across",
  "act",
  "action",
  "active",
  "activity",
  "actor",
  "actress",
  "actual",
  "actually",
  "ad",
  "adapt",
  "add",
  "addition",
  "additional",
  "address",
  "administration",
  "admire",
  "admit",
  "adopt",
  "adult",
  "advance",
  "advanced",
  "advantage",
  "adventure",
  "advertise",
  "advertisement",
  "advertising",
  "advice",
  "advise",
  "affair",
  "affect",
  "afford",
  "afraid",
  "after",
  "afternoon",
  "afterwards",
  "again",
  "against",
  "age",
  "agency",
  "agenda",
  "agent",
  "aggressive",
  "ago",
  "agree",
  "agreement",
  "ah",
  "ahead",
  "aid",
  "aim",
  "air",
  "aircraft",
  "airline",
  "airport",
  "alarm",
  "album",
  "alcohol",
  "alcoholic",
  "alive",
  "all",
  "all right",
  "allow",
  "almost",
  "alone",
  "along",
  "already",
  "also",
  "alter",
  "alternative",
  "although",
  "always",
  "amazed",
  "amazing",
  "ambition",
  "ambitious",
  "among",
  "amount",
  "analyse",
  "analysis",
  "ancient",
  "and",
  "anger",
  "angle",
  "angry",
  "animal",
  "ankle",
  "anniversary",
  "announce",
  "announcement",
  "annoy",
  "annoyed",
  "annoying",
  "annual",
  "another",
  "answer",
  "anxious",
  "any",
  "anybody",
  "any more",
  "anyone",
  "anything",
  "anyway",
  "anywhere",
  "apart",
  "apartment",
  "apologize",
  "app",
  "apparent",
  "apparently",
  "appeal",
  "appear",
  "appearance",
  "apple",
  "application",
  "apply",
  "appointment",
  "appreciate",
  "approach",
  "appropriate",
  "approval",
  "approve",
  "approximately",
  "April",
  "architect",
  "architecture",
  "area",
  "argue",
  "argument",
  "arise",
  "arm",
  "armed",
  "arms",
  "army",
  "around",
  "arrange",
  "arrangement",
  "arrest",
  "arrival",
  "arrive",
  "art",
  "article",
  "artificial",
  "artist",
  "artistic",
  "as",
  "ashamed",
  "ask",
  "asleep",
  "aspect",
  "assess",
  "assessment",
  "assignment",
  "assist",
  "assistant",
  "associate",
  "associated",
  "association",
  "assume",
  "at",
  "athlete",
  "atmosphere",
  "attach",
  "attack",
  "attempt",
  "attend",
  "attention",
  "attitude",
  "attract",
  "attraction",
  "attractive",
  "audience",
  "August",
  "aunt",
  "author",
  "authority",
  "autumn",
  "available",
  "average",
  "avoid",
  "award",
  "aware",
  "away",
  "awful",
  "baby",
  "back",
  "background",
  "backwards",
  "bacteria",
  "bad",
  "badly",
  "bag",
  "bake",
  "balance",
  "ball",
  "ban",
  "banana",
  "band",
  "bank (money)",
  "bank (river)",
  "bar",
  "barrier",
  "base",
  "baseball",
  "based",
  "basic",
  "basically",
  "basis",
  "basketball",
  "bath",
  "bathroom",
  "battery",
  "battle",
   "be v., auxiliary",
  "beach",
"bean",
  "bear (deal with)",
  "bear (animal) ",
  "beat",
  
  // ... add the rest of the words here ...
];

// Create list items dynamically
const list = document.getElementById("checkbox-list");
words.forEach((word) => {
  const li = document.createElement("li");
  const checkbox = document.createElement("input");
  checkbox.type = "checkbox";
  checkbox.id = word;
  const label = document.createElement("label");
  label.textContent = word;
  label.htmlFor = word;
  li.appendChild(checkbox);
  li.appendChild(label);
  list.appendChild(li);
});

// Store checked state in local storage
const storage = window.localStorage;
list.addEventListener("change", (event) => {
  if (event.target.type === "checkbox") {
    const id = event.target.id;
    const checked = event.target.checked;
    storage.setItem(id, checked);
  }
});

// Restore checked state from local storage
words.forEach((word) => {
  const checkbox = document.getElementById(word);
  const checked = storage.getItem(word) === "true";
  checkbox.checked = checked;
});